name: GitHub Actions For ModuleDocs
run-name: ${{ github.actor }} is running the workflow to push the latest code or re-generate the module docs
on:
  push:
    branches:
      - main
jobs:
  Module-Docs-Build-Sphinx-For-All-Modules:
    name: Build Complete Sphinx documentation
    runs-on: ubuntu-latest
    steps:
      - name: Print context info
        run: | 
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."

      - name: Check out module docs repository code
        uses: actions/checkout@v3
        with:
          path: moduleDocs

      - name: Checkout stackrModule
        uses: actions/checkout@v3
        with:
          repository: tunix78/stackrModule
          token: ${{ secrets.STACKR_MODULE_ACCESS_PAT }}
          path: modules/stackrModule

      - name: Merge module directories into master docs
        run: |
          cd moduleDocs/scripts
          ./merge_docs_folders.sh ${{ github.workspace }} modules moduleDocs tgt_module_docs_dir

      #- name: Build the sphinx documentation
      #  run: |
      #    cd moduleDocs/scripts
      #    ./build_module_docs.sh ${{ github.workspaces }}/tgt_module_docs_dir

      - name: List files in the repository
        run: |
          ls -lRrt ${{ github.workspace }}

      - name: Do the Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "tgt_module_docs_dir/docs"

      - name: List files in the moduleDocs repository
        run: |
          ls -lRrt tgt_module_docs_dir/

      - name: Upload sphinx overall docs to static website in Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --overwrite --account-name svensappstorage --auth-mode key -d '$web/docs/moduleDocs' -s tgt_module_docs_dir/docs/build/html
      
      - name: Print job status
        run: |
          echo "This job's status is ${{ job.status }}."
