name: GitHub Actions For ModuleDocs
run-name: ${{ github.actor }} is running the workflow to push the latest code or re-generate the module docs
on:
  push:
    branches:
      - main
jobs:
  Module-Docs-Build-Sphinx-For-All-Modules:
    name: Build Complete Sphinx documentation
    runs-on: ubuntu-latest
    steps:
      - name: Print context info
        run: | 
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Check out module docs repository code
        uses: actions/checkout@v3
        with:
          path: module-docs
      - name: Checkout all terraform module repositories
        uses: actions/checkout@v3
        with:
          repository: tunix78/stackrModule
          token: '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'
          path: stackr-module
      - name: List files in the repository
        run: |
          ls -lrt ${{ github.workspace }}
      - name: Do the Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: Print job status
        run: |
          echo "This job's status is ${{ job.status }}."
